import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Image from "next/image";

export default function Home() {
  const [inputValue, setInputValue] = useState<number>();
  const [exchangeValue, setExchangeValue] = useState<number>()

  const fetchExchangeValue = async () => {
    const response = await fetch(process.env.API_URL || "", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ value: inputValue }),
    });

    const data = await response.json();

    if (data.exchangeValue) {
      setExchangeValue(data.exchangeValue);
    }
  }


  const handleButtonClick = () => {
    if (exchangeValue) {
      setInputValue(undefined);
      setExchangeValue(undefined);
    } else {
      fetchExchangeValue();
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.form}>
          <div className={styles.wrapper}>
            <Image src="/euro.svg" alt="euro" width={20} height={20} />
            {!exchangeValue ? (
              <input
                onChange={(event) => setInputValue(+((+event.target.value).toFixed(2)))}
                className={styles.input}
                value={inputValue}
                type="number"
                min={0}
              />
            ) : <div className={styles.exchangeValue}>
              {`${inputValue} EUR = ${exchangeValue} PLN`}
            </div>}
          </div>
          <div className={styles.button} onClick={handleButtonClick}>{exchangeValue ? "exchange again" : "exchange to PLN"}</div>
        </div>
      </div>
    </>
  );
}
